FROM python:3.11-slim

WORKDIR /app

# Copy project files
COPY . .

# Exclude set_password.py (it will remain outside the container)
RUN rm -f set_password.py

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port (adjust as needed for your application)
EXPOSE 8000

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Run your application
CMD ["python", "main.py"]